version: '3'

services: 
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - nginx

  jira-plugin:
    restart: always
    image: 'jadyoung/eiffel-jira-plugin:0.0.1-SNAPSHOT'
    environment:
      rabbitmq.host: rabbit
    networks:
      default:
        aliases:
          - jira-plugin

  rabbit:
    restart: always
    image: 'rabbitmq:3.7.4-management'
    networks:
      default:
          aliases:
            - rabbit

  store:
    restart: always
    image: jadyoung/eiffel-store:0.0.1
    environment: 
      ROOT_URL: http://eiffel.jadyoung.com/visualization
      MONGO_URL: mongodb://mongo:27017/meteor
    depends_on: 
      - mongo
    networks:
      default:
        aliases:
          - store
  
  mongo:
    restart: always
    image: mongo:3.7
    networks:
      default:
        aliases:
          - mongo

  publish:
    image: jadyoung/publish-file-to-rabbit:latest
    environment:
      RABBIT_HOST: rabbit
      RABBIT_EXCHANGE_NAME: eiffel
      RABBIT_ROUTING_KEY: eiffel
      EVENTS_FILE: data/events.json
      EVENTS_LIMIT: 99999999
    volumes:
      - ./publish/:/root/data/
    networks:
      default:
        aliases:
          - publish
    depends_on:
      - rabbit

  plumb-rabbit-to-mongo:
    restart: always
    image: jadyoung/plumb-rabbit-to-mongo:latest
    depends_on:
      - rabbit
      - mongo
    environment:
      MONGO_URI: mongodb://mongo/meteor
      MONGO_COLLECTION: eiffel-events
      RABBIT_URI: amqp://guest:guest@rabbit:5672/
      RABBIT_QUEUE_NAME: vici
      RABBIT_EXCHANGE: eiffel
    networks:
      default:
        aliases:
          - plumb-rabbit-to-mongo

  mongo-express:
    restart: always
    image: mongo-express
    command: ./app.js -H mongo
    networks:
      default:
        aliases:
          - mongo-express
